// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var demos, methods;
    if (!OriDomi.isSupported) {
      document.getElementById('unsupported').style.display = 'block';
      return;
    }
    demos = [
      new OriDomi('.demo3', {
        vPanels: 8,
        ripple: true
      })
    ];
    setTimeout(function() {
      return demos[0].twist(-73);
    }, 1000);
    methods = ['accordion', 'curl', 'reveal', 'fracture', 'ramp', 'stairs', 'twist'];
    return document.getElementById('demos').addEventListener('click', function(e) {
      var angle, el, method, n;
      if ((el = e.target).className !== 'button') {
        return;
      }
      n = el.getAttribute('data-n');
      method = methods[Math.floor(Math.random() * methods.length)];
      angle = Math.floor(Math.random() * 80 * (Math.random() > .5 ? -1 : 1));
      demos[n][method](method !== 'foldUp' ? angle : void 0);
      return el.parentNode.getElementsByClassName('label')[0].innerHTML = "" + method + "(" + angle + ")";
    }, false);
  });

}).call(this);
