// Generated by CoffeeScript 1.6.3
(function() {
    document.addEventListener('DOMContentLoaded', function() {
        var demo, methods;
        if (!OriDomi.isSupported) {
          document.getElementById('unsupported').style.display = 'block';
          document.getElementsByClassName('controls')[0].style.display = 'none';
          return;
        }
        demo = new OriDomi('.demo3', {
            vPanels: 8,
            ripple: true
        });

        setTimeout(function() {
            return demo.twist(-73);
        }, 1500);

        methods = ['accordion', 'curl', 'reveal', 'fracture', 'ramp', 'stairs', 'twist'];

        return document.getElementById('fold').addEventListener('click', function(e) {

            var angle, el, method, n;
            el = e.target;
            method = methods[Math.floor(Math.random() * methods.length)];
            angle = Math.floor(Math.random() * 80 * (Math.random() > .5 ? -1 : 1));
            demo[method](angle);
            return el.parentNode.getElementsByClassName('label')[0].innerHTML = "" + method + "(" + angle + ")";

        }, false);

    });

}).call(this);