# Generated by CoffeeScript 1.7.1
(->
  document.addEventListener "DOMContentLoaded", ->
    btn_fold = document.getElementById("fold")
    demo = new OriDomi(".demo3",
      vPanels: 9
      ripple: true
      shading: false
    )
    methods = [
      "accordion"
      "fracture"
      "stairs"
      "twist"
    ]
    setTimeout (->
      btn_fold.click()
    ), 1900
    btn_fold.addEventListener "click", ((e) ->
      el = e.target
      method = methods[Math.floor(Math.random() * methods.length)]
      angle = Math.floor(Math.random() * 80 * ((if Math.random() > .5 then -1 else 1)))
      demo[method] angle
      el.parentNode.getElementsByClassName("label")[0].innerHTML = method + "(" + angle + ")"
    ), false

).call this
