// Generated by CoffeeScript 1.7.1
(function() {
  return document.addEventListener("DOMContentLoaded", function() {
    var btn_fold, demo, methods;
    btn_fold = document.getElementById("fold");
    demo = new OriDomi(".demo3", {
      vPanels: 9,
      ripple: true,
      shading: false
    });
    methods = ["accordion", "fracture", "stairs", "twist"];
    setTimeout((function() {
      return btn_fold.click();
    }), 1900);
    return btn_fold.addEventListener("click", (function(e) {
      var angle, el, method;
      el = e.target;
      method = methods[Math.floor(Math.random() * methods.length)];
      angle = Math.floor(Math.random() * 80 * (Math.random() > .5 ? -1 : 1));
      demo[method](angle);
      return el.parentNode.getElementsByClassName("label")[0].innerHTML = method + "(" + angle + ")";
    }), false);
  });
}).call(this);
